film_ocean/config/routes.rb
Rails.application.routes.draw do

  get 'film_logos/index'

  get 'film_logos/new'

  get 'film_logos/edit'

  root 'website/films#index'

  namespace :backend do
    root 'admins#index'

    resources :film_titles
  end

end

film_ocean/app/models/file_logo.rb
class FileLogo < ActiveRecord::Base
end

film_ocean/app/models/film.rb
class Film < ActiveRecord::Base
	has_and_belongs_to_many :film_categories
	has_and_belongs_to_many :film_directors
	has_and_belongs_to_many :film_actors
	has_many :film_downloads
	has_one :film_title
	has_one :film_logo
	has_one :film_area
	has_one :film_introduction
end

film_ocean/app/models/film_actor.rb
class FilmActor < ActiveRecord::Base
	has_and_belongs_to_many :films
end

film_ocean/app/models/film_area.rb
class FilmArea < ActiveRecord::Base
end

film_ocean/app/models/film_category.rb
class FilmCategory < ActiveRecord::Base
	has_and_belongs_to_many :films
end

film_ocean/app/models/film_director.rb
class FilmDirector < ActiveRecord::Base
	has_and_belongs_to_many :films
end

film_ocean/app/models/film_download.rb
class FilmDownload < ActiveRecord::Base
end

film_ocean/app/models/film_introduction.rb
class FilmIntroduction < ActiveRecord::Base
end

film_ocean/app/models/film_title.rb
class FilmTitle < ActiveRecord::Base
end

film_ocean/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

film_ocean/app/controllers/backend/admins_controller.rb
module Backend
	class AdminsController < Backend::ApplicationController
		def index
		end
	end
end

film_ocean/app/controllers/backend/application_controller.rb
module Backend
	class ApplicationController < ActionController::Base
		protect_from_forgery with: :exception
		layout 'backend'
	end
end

film_ocean/app/controllers/backend/film_titles_controller.rb
module Backend
	class FilmTitlesController < Backend::ApplicationController
		before_action :find_film_title, only: [:edit, :update, :destroy]

		def index
			@film_titles = FilmTitle.all
		end

		def new
			@film_title = FilmTitle.new
		end

		def create
			@film_title = FilmTitle.new(film_title_params)
			if @film_title.save
				redirect_to backend_film_titles_path, notice: '新增成功!'
			else
				@film_title = FilmTitle.new
				render action: :new
			end
		end

		def show
		end

		def edit
		end

		def update
			if @film_title.update(film_title_params)
				redirect_to backend_film_titles_path, notice: '修改成功!'
			else
				render edit_backend_film_titles_path(@film_title), notice: '修改失败!'
			end
		end
		def destroy
			notice = '删除成功!'
			if !@film_title.destroy
				notice = '删除失败!'
			end
			redirect_to backend_film_titles_path, notice: notice
		end

		private
		def find_film_title
			@film_title = FilmTitle.find(params[:id])
		end

		def film_title_params
			params.require(:film_title).permit(:chinese_name, :english_name, :id)
		end
	end
end

film_ocean/app/controllers/backend/films_controller.rb
module Backend
	class FilmsController < Backend::ApplicationController
		def index
			
		end
	end
end

film_ocean/app/controllers/film_logos_controller.rb
class FilmLogosController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end
end

film_ocean/app/controllers/website/application_controller.rb
module Website
	class ApplicationController < ActionController::Base
		protect_from_forgery with: :exception
		layout 'website'
	end
end

film_ocean/app/controllers/website/films_controller.rb
module Website
	class FilmsController < Website::ApplicationController
		def index
			@films = Film.all
		end

		def film_detail
		end
	end
end

film_ocean/app/helpers/application_helper.rb
module ApplicationHelper

	#
	# 后端的导航
	#
	def backend_nvigation
		controller_name = params[:controller].to_s.gsub 'backend/',''
		action_name = params[:action]

		navigation_index = backend_navigations.index{ |item| item.key == controller_name }
		navigation_index = 0 if navigation_index.blank?
		navigation = backend_navigations[navigation_index]

		result = <<-EOF
        <div class="header">
            <h1 class="page-title">#{navigation.name}</h1>
			<ul class="breadcrumb">
		EOF

		if navigation_index != 0
			result << "<li><a href='#{backend_root_path}'>首页</a></li>"
			if action_name == 'index'
				result << "<li class='active'>#{navigation.name}</li>"
			else
				result << "<li><a href='../../../#{navigation.name_value}'>#{navigation.name}</a></li>"
				result << "<li class='active'>#{navigation.sub_navigations[action_name]}</li>"
			end
		else
			result << "<li class='active'>首页</li>"
		end

		result << '</ul>'
        result << '</div>'

		raw result
	end

	private
	def backend_navigations
		navigations = []
		conrollers = %w(admins film_titles film_logos films film_actors film_areas film_categories film_directors film_downloads film_introductions)
		names = %w(首页 名称管理 Logo管理 影片管理 演员管理 区域管理 分类管理 导演管理 下载地址管理 简介管理)

		conrollers.each_with_index do |c,index|
			menu_navigation = MenuNavigation.new
			menu_navigation.key = c
			menu_navigation.name = names[index]
			menu_navigation.name_value = 'backend/' + c
			navigations.push menu_navigation
		end
		return navigations
	end
end

film_ocean/app/helpers/film_logos_helper.rb
module FilmLogosHelper
end

film_ocean/app/views/backend/admins/index.html.erb
<!-- 
    <div class="content">
        <div class="header">
            <div class="stats">
    <p class="stat"><span class="label label-info">5</span> Tickets</p>
    <p class="stat"><span class="label label-success">27</span> Tasks</p>
    <p class="stat"><span class="label label-danger">15</span> Overdue</p>
</div>

            <h1 class="page-title">Dashboard</h1>
                    <ul class="breadcrumb">
            <li><a href="index.html">Home</a> </li>
            <li class="active">Dashboard</li>
        </ul>

        </div>
    </div>

    <script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script> -->

film_ocean/app/views/backend/film_titles/_form.html.erb
<div class="main-content">

<div class="row">
  <div class="col-md-4">
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active in" id="home">

      <%= form_for [:backend, @film_title]  do |f| %>
        <div class="form-group">
          <label>中文名</label>
          <%=f.text_field :chinese_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label>英文名</label>
          <%= f.text_field :english_name, class: 'form-control' %>
        </div>

        <div class="btn-toolbar list-toolbar">
          <%= f.submit '保存', class: 'btn btn-primary' %>
          <%= link_to '返回', backend_film_titles_path , class: 'btn btn-primary' %>

        </div>
      <% end %>

  </div>
</div>

film_ocean/app/views/backend/film_titles/edit.html.erb
<%= render 'form' %>

film_ocean/app/views/backend/film_titles/index.html.erb
    <div class="main-content">

<div class="btn-toolbar list-toolbar">
    <a href="<%= new_backend_film_title_path %>" class="btn btn-primary"><i class="fa fa-plus"></i> 新增</a>
    <a href="#" class="btn btn-default">导入</a>
    <a href="#" class="btn btn-default">导出</a>
    <a href="#" class="btn btn-default">下载模板</a>
  <div class="btn-group">
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>中文名</th>
      <th>英文名</th>
      <th style="width: 3.5em;"></th>
    </tr>
  </thead>
  <tbody>
  <% @film_titles.each do |title| %>
    <tr>
      <td><%= title.chinese_name %></td>
      <td><%= title.english_name%></td>
      <td>
          <a href="<%= edit_backend_film_title_path title %>"><i class="fa fa-pencil"></i></a>
          <a href="<%= backend_film_title_path title%>" data-confirm="确定删除吗?" data-method="delete" role="button" data-toggle="modal"><i class="fa fa-trash-o"></i></a>
      </td>
    </tr>
   <% end %>
  </tbody>
</table>

<ul class="pagination">
  <li><a href="#">&laquo;</a></li>
  <li><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">4</a></li>
  <li><a href="#">5</a></li>
  <li><a href="#">&raquo;</a></li>
</ul>

film_ocean/app/views/backend/film_titles/new.html.erb
<%= render 'form' %>

film_ocean/app/views/backend/shared/_confirm.html.erb
<div class="modal small fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Delete Confirmation</h3>
        </div>
        <div class="modal-body">
            <p class="error-text"><i class="fa fa-warning modal-icon"></i>Are you sure you want to delete the user?<br>This cannot be undone.</p>
        </div>
        <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button class="btn btn-danger" data-dismiss="modal">Delete</button>
        </div>
      </div>
    </div>
</div>

film_ocean/app/views/backend/shared/_footer.html.erb
<footer>
    <hr>
    <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Portnine</a></p>
    <p>© 2014 <a href="http://www.portnine.com" target="_blank">Portnine</a></p>
</footer>

film_ocean/app/views/backend/shared/_header.html.erb
<div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="" href="index.html"><span class="navbar-brand"><span class="fa fa-paper-plane"></span> 影海拾贝管理后台</span></a></div>

    <div class="navbar-collapse collapse" style="height: 1px;">
      <ul id="main-menu" class="nav navbar-nav navbar-right">
        <li class="dropdown hidden-xs">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-user padding-right-small" style="position:relative;top: 3px;"></span> Jack Smith
                <i class="fa fa-caret-down"></i>
            </a>

          <ul class="dropdown-menu">
            <li><a href="./">My Account</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Admin Panel</li>
            <li><a href="./">Users</a></li>
            <li><a href="./">Security</a></li>
            <li><a tabindex="-1" href="./">Payments</a></li>
            <li class="divider"></li>
            <li><a tabindex="-1" href="sign-in.html">Logout</a></li>
          </ul>
        </li>
      </ul>

    </div>
  </div>

film_ocean/app/views/backend/shared/_menu.html.erb
<div class="sidebar-nav">
    <ul>
    	<li>
	    	<a href="#" data-target=".dashboard-menu" class="nav-header" data-toggle="collapse">
	    	<i class="fa fa-fw fa-dashboard"></i> 资源管理<i class="fa fa-collapse"></i></a>
    	</li>
    	<li>
	    	<ul class="dashboard-menu nav nav-list collapse in">
	            <li><a href="index.html"><span class="fa fa-caret-right"></span> 影片管理</a></li>
	            <li ><a href="<%= backend_film_titles_path %>"><span class="fa fa-caret-right"></span> 名称管理</a></li>
	            <li ><a href="user.html"><span class="fa fa-caret-right"></span> Logo管理</a></li>
	            <li ><a href="media.html"><span class="fa fa-caret-right"></span> 导演管理</a></li>
	            <li ><a href="calendar.html"><span class="fa fa-caret-right"></span> 区域管理</a></li>
	            <li ><a href="calendar.html"><span class="fa fa-caret-right"></span> 演员管理</a></li>
	            <li ><a href="calendar.html"><span class="fa fa-caret-right"></span> 简介管理</a></li>
                <li ><a href="calendar.html"><span class="fa fa-caret-right"></span> 分类管理</a></li>
                <li ><a href="calendar.html"><span class="fa fa-caret-right"></span> 下载地址管理</a></li>
	        </ul>
    	</li>

    	<li data-popover="true" data-content="Items in this group require a <strong><a href='http://portnine.com/bootstrap-themes/aircraft' target='blank'>premium license</a><strong>." rel="popover" data-placement="right"><a href="#" data-target=".premium-menu" class="nav-header collapsed" data-toggle="collapse"><i class="fa fa-fw fa-fighter-jet"></i> Premium Features<i class="fa fa-collapse"></i></a></li>
        <li>
        	<ul class="premium-menu nav nav-list collapse">
                <li class="visible-xs visible-sm">
                <a href="#">- Premium features require a license -</a></span>
            <li ><a href="premium-profile.html"><span class="fa fa-caret-right"></span> Enhanced Profile</a></li>
            <li ><a href="premium-blog.html"><span class="fa fa-caret-right"></span> Blog</a></li>
            <li ><a href="premium-blog-item.html"><span class="fa fa-caret-right"></span> Blog Page</a></li>
            <li ><a href="premium-pricing-tables.html"><span class="fa fa-caret-right"></span> Pricing Tables</a></li>
            <li ><a href="premium-upgrade-account.html"><span class="fa fa-caret-right"></span> Upgrade Account</a></li>
            <li ><a href="premium-widgets.html"><span class="fa fa-caret-right"></span> Widgets</a></li>
            <li ><a href="premium-timeline.html"><span class="fa fa-caret-right"></span> Activity Timeline</a></li>
            <li ><a href="premium-users.html"><span class="fa fa-caret-right"></span> Enhanced Users List</a></li>
            <li ><a href="premium-media.html"><span class="fa fa-caret-right"></span> Enhanced Media</a></li>
            <li ><a href="premium-invoice.html"><span class="fa fa-caret-right"></span> Invoice</a></li>
            <li ><a href="premium-build.html"><span class="fa fa-caret-right"></span> Advanced Tools</a></li>
            <li ><a href="premium-colors.html"><span class="fa fa-caret-right"></span> Additional Color Themes</a></li>
    		</ul>
    </li>

        <li>
        <a href="#" data-target=".accounts-menu" class="nav-header collapsed" data-toggle="collapse"><i class="fa fa-fw fa-briefcase"></i> 用户管理 <i class="fa fa-collapse"></i></a></li>
        <li>
        	<ul class="accounts-menu nav nav-list collapse">
	            <li ><a href="sign-in.html"><span class="fa fa-caret-right"></span> 角色管理</a></li>
	            <li ><a href="sign-up.html"><span class="fa fa-caret-right"></span> 权限管理</a></li>
	            <li ><a href="reset-password.html"><span class="fa fa-caret-right"></span> 成员管理</a></li>
    		</ul>
    	</li>

        <li>
        	<a href="#" data-target=".legal-menu" class="nav-header collapsed" data-toggle="collapse"><i class="fa fa-fw fa-legal"></i> 工具管理<i class="fa fa-collapse"></i></a></li>
        	<li>
	        	<ul class="legal-menu nav nav-list collapse">
	            	<li ><a href="privacy-policy.html"><span class="fa fa-caret-right"></span> 爬虫管理</a></li>
	            	<li ><a href="terms-and-conditions.html"><span class="fa fa-caret-right"></span> Terms and Conditions</a></li>
	    		</ul>
    		</li>

        <li><a href="help.html" class="nav-header"><i class="fa fa-fw fa-question-circle"></i> Help</a></li>
            <li><a href="faq.html" class="nav-header"><i class="fa fa-fw fa-comment"></i> Faq</a></li>
                <li><a href="http://portnine.com/bootstrap-themes/aircraft" class="nav-header" target="blank"><i class="fa fa-fw fa-heart"></i> Get Premium</a></li>
            </ul>
    </div>

film_ocean/app/views/film_logos/edit.html.erb
<h1>FilmLogos#edit</h1>
<p>Find me in app/views/film_logos/edit.html.erb</p>

film_ocean/app/views/film_logos/index.html.erb
<h1>FilmLogos#index</h1>
<p>Find me in app/views/film_logos/index.html.erb</p>

film_ocean/app/views/film_logos/new.html.erb
<h1>FilmLogos#new</h1>
<p>Find me in app/views/film_logos/new.html.erb</p>

film_ocean/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilmOcean</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

film_ocean/app/views/layouts/backend.html.erb
<!doctype html>
<html lang="en"><head>
    <meta charset="utf-8">
    <title>Bootstrap Admin</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag 'backend', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'backend', 'data-turbolinks-track' => true %>

   <script type="text/javascript">
        $(function() {
            $(".knob").knob();
        });
    </script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


    <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
    <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
    <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
    <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
    <!--[if (gt IE 9)|!(IE)]><!-->
    <!--<![endif]-->

    <%= csrf_meta_tags %>
</head>
<body class=" theme-blue">
    <script type="text/javascript">
        $(function() {
            var match = document.cookie.match(new RegExp('color=([^;]+)'));
            if(match) var color = match[1];
            if(color) {
                $('body').removeClass(function (index, css) {
                    return (css.match (/\btheme-\S+/g) || []).join(' ')
                })
                $('body').addClass('theme-' + color);
            }

            $('[data-popover="true"]').popover({html: true});
        });
    </script>
    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .navbar-default .navbar-brand, .navbar-default .navbar-brand:hover { 
            color: #fff;
        }
    </style>

    <script type="text/javascript">
        $(function() {
            var uls = $('.sidebar-nav > ul > *').clone();
            uls.addClass('visible-xs');
            $('#main-menu').append(uls.clone());
        });
    </script>

    <%= render 'backend/shared/header' %>
    <%= render 'backend/shared/menu' %>

    <div class="content">
    <%= backend_nvigation %>

	<%= yield %>

    <%= render 'backend/shared/confirm' %>
    <%= render 'backend/shared/footer' %>

    </div>
    </div>
</body>
</html>

film_ocean/app/views/layouts/website.html.erb
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<%= stylesheet_link_tag 'website', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'website', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body style="width:100%">
<div  id="LG">
	<%= yield %>
</div>

</body>
</html>

film_ocean/app/views/website/films/film_detail.html.erb
<div class="row-fluid">
	<div class="span8" id="span8">

		<%= render 'website/shared/head' %>
		<%= render 'website/shared/navigation' %>

		<div class="row-fluid">
			<div class="span8">
				<div class="page-header">
					<h1>
						大菠萝哈哈哈 <small>daboluohahaha</small>
					</h1>
				</div>
				<img width="300px" src="./images/mingxi.jpg" class="img-rounded" />
				<br/><br/>
				<div class="accordion" id="accordion">
					<div class="accordion-group">
						<div class="accordion-heading">
							 <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#accordion-element-a">基本信息</a>
						</div>
						<div id="accordion-element-a" class="accordion-body in">
							<div class="accordion-inner">
<p>导演: 王家卫</p>
<p>编剧: 王家卫 / 金庸</p>
<p>主演: 张国荣 / 张曼玉 / 梁朝伟 / 林青霞 / 张学友/ 更多...</p>
<p>类型: 剧情 / 动作 / 爱情 / 武侠 / 古装</p>
<p>制片国家/地区: 香港 / 台湾</p>
<p>语言: 粤语 / 汉语普通话</p>
<p>上映日期: 1994-09-17(中国大陆)</p>
<p>片长: 100 分钟 / 93 分钟(修复版)</p>
<p>又名: Ashes of Time</p>
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							 <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#accordion-element-b">简介</a>
						</div>
						<div id="accordion-element-b" class="accordion-body in">
							<div class="accordion-inner">
								 在恋人（张曼玉）负气嫁给兄长的当晚，欧阳锋（张国荣）黯然离开白陀山，走进沙漠某个小镇，成为一名杀手中介人。他的朋友、风流剑客黄药师（梁家辉）每年都来小镇与他畅饮，酒话里有关白陀山的消息令他忘却往事的念想渐次演变成自欺行为。
黄药师只是表面风流。他迷恋好友“盲武士”（梁朝伟）的妻子桃花（刘嘉玲），后者在丈夫死后，永远地离开了他；而对迷恋他的女人慕容嫣（林青霞），他又不愿兑现曾经随口说出的承诺，这使得慕容嫣迷失于自己的身份中。与欧阳锋构成短暂“买凶杀人”关系的洪七（张学友）、村姑（杨采妮）等人，也都有一段只有他们自己才知、不愿回首的痛苦过往。
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							 <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#accordion-element-c">下载地址</a>
						</div>
						<div id="accordion-element-c" class="accordion-body in">
							<div class="accordion-inner">
								<p>非直接下载地址: https://google.com</p>
								<p>直接下载地址: https://google.com</p>
								<p>百度云盘地址: https://google.com</p>
								<p>百度云盘密码: https://google.com</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="span3" id="detail_right">
				<div>
					<span>贝壳分类</span><br/>
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
					<span class="label">标签</span> 
				</div>
				<br/>
				<div class="tabbable" id="tabs">
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#panel-a" data-toggle="tab">最热贝壳</a>
						</li>
						<li>
							<a href="#panel-b" data-toggle="tab">拾个贝壳</a>
						</li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="panel-a">
							<p>aaaaaaaaaaaaaaaaaa</p>
							<p>aaaaaaaaaaaaaaaaaa</p>
							<p>aaaaaaaaaaaaaaaaaa</p>
							<p>aaaaaaaaaaaaaaaaaa</p>
							<p>aaaaaaaaaaaaaaaaaa</p>
						</div>
						<div class="tab-pane" id="panel-b">
							<p>bbbbbbbbbbbbbbbbbb</p>
							<p>bbbbbbbbbbbbbbbbbb</p>
							<p>bbbbbbbbbbbbbbbbbb</p>
							<p>bbbbbbbbbbbbbbbbbb</p>
							<p>bbbbbbbbbbbbbbbbbb</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

film_ocean/app/views/website/films/index.html.erb
<div class="row-fluid">
	<div class="span8" id="span8">

		<%= render 'website/shared/head' %>
		<%= render 'website/shared/marquee' %>

		<div class="row-fluid">
			<div class="span12">
				<ul class="thumbnails">
					<% @films.each do |film| %>
						<li class="span3">
							<div class="thumbnail">
								<a href="./detail.html">
									<img alt="<%= film.chinese_name %>" width="300" title='<%= film.chinese_name %>' src="<%= asset_path('tmp.png') %>" />
								</a>
								<div class="caption description">
									<h3 class="txt_ellipsis">
										<%= film.chinese_name %>
									</h3>
									<p class="txt_ellipsis">
										简介：<%= film.chinese_name %>
									</p>
									<ul>
										<li class="description_li_1">
											<i class="icon-calendar description_li_i"></i><span>2015-10-21</span>
										</li>
										<li class="description_li_2">
											<i class="icon-eye-open description_li_i"></i><span>10000000</span>
										</li>
										<li class="description_li_3">
											<i class="icon-star description_li_i"></i>
											<i class="icon-star description_li_i"></i>
											<i class="icon-star description_li_i"></i>
											<i class="icon-star description_li_i"></i>
											<i class="icon-star-empty description_li_i"></i>
										</li>
									</ul>
								</div>
							</div>
						</li>
					<% end %>



				</ul>
				<div class="pagination pagination-right pagination-small pagination_div">
					<ul>
						<li>
							<a href="#">上一页</a>
						</li>
						<li>
							<a href="#">1</a>
						</li>
						<li>
							<a href="#">2</a>
						</li>
						<li>
							<a href="#">3</a>
						</li>
						<li>
							<a href="#">4</a>
						</li>
						<li>
							<a href="#">5</a>
						</li>
						<li>
							<a href="#">下一页</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

film_ocean/app/views/website/shared/_head.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container-fluid">
			 <a data-target=".navbar-responsive-collapse" data-toggle="collapse" class="btn btn-navbar"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a> <a href="#" class="brand">影海拾贝</a>
			<div class="nav-collapse collapse navbar-responsive-collapse">
				<ul class="nav">
					<li class="active">
						<a href="./webpage.html">首页</a>
					</li>
					<li>
						<a href="#">最新贝壳</a>
					</li>
					<li>
						<a href="./about.html">关于</a>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li>
						<!-- <a href="#">右边链接</a> -->
						<input type="text"  id="search" placeholder="输入关键字后搜索...">
						<span class="add-on btn" id="search_btn">搜索</span>
					</li>
					<li class="divider-vertical">
					</li>
				</ul>
			</div>
		</div>
	</div>

film_ocean/app/views/website/shared/_marquee.html.erb
	<ul class="marquee">
		<li>
			<div id="marquee" data-duplicated='true'>
				免责声明: 开发本站的目的只是为了学习Ruby On Rails. 本站仅供测试和学习交流.
			</div>
		</li>
	</ul>
</div>

film_ocean/app/views/website/shared/_navigation.html.erb
	<ul class="breadcrumb">
		<li>
		  <a href="#">首页</a> <span class="divider">/</span>
		</li>
		<li>
		  <a href="#">明细</a> <span class="divider">/</span>
		</li>
		<li class="active">
		  大菠萝哈哈哈
		</li>
	</ul>
</div>